package catchthepattern.com.afilters;

public enum EnumOp {
    IS_GREATER_THAN,
    IS_SMALLER_THAN,
    IS_WITHIN_HALF_PERCENT_OF,
    IS_WITHIN_1_PERCENT_OF,
    IS_WITHIN_2_PERCENT_OF,
    IS_WITHIN_3_PERCENT_OF,
    IS_WITHIN_4_PERCENT_OF,
    IS_WITHIN_5_PERCENT_OF,
    IS_WITHIN_6_PERCENT_OF,
    IS_WITHIN_10_PERCENT_OF,
    IS_WITHIN_15_PERCENT_OF,
    IS_WITHIN_20_PERCENT_OF,
    
}
